GET http://localhost:8000/api/products/ HTTP/1.1

### 

POST http://localhost:8000/api/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgxMTEyODg5LCJpYXQiOjE3ODExMTI1ODksImp0aSI6ImY3MDc2MjUwNzFmMDQyMjJhYWIzMzQ0NjRkNGQzNWRlIiwidXNlcl9pZCI6IjIifQ.1BolMPkls2O3JPs433PHPKqmWF4DUIDNHtfwta37Khk

{
  "name": "Television",
  "price": 300.00,
  "stock": 14,
  "description": "An amazing new TV."
}


###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "test"
}

###

# we can get access token using refresh token
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4MTE5OTI2MCwiaWF0IjoxNzgxMTEyODYwLCJqdGkiOiIxYjQ4ZTNkN2VmNWM0YzBjODNhYmI3MTJlYzA4Y2E3YiIsInVzZXJfaWQiOiIyIn0.uyo-JapF_DhcHPEIPERstxK1X4C6Mgt5AVfsVSlI4Rw"
}

###

GET http://localhost:8000/api/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgxMTEyODg5LCJpYXQiOjE3ODExMTI1ODksImp0aSI6ImY3MDc2MjUwNzFmMDQyMjJhYWIzMzQ0NjRkNGQzNWRlIiwidXNlcl9pZCI6IjIifQ.1BolMPkls2O3JPs433PHPKqmWF4DUIDNHtfwta37Khk


### 

GET http://localhost:8000/api/products/1/ HTTP/1.1

### 

PUT  http://localhost:8000/api/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgxMTE0Nzc0LCJpYXQiOjE3ODExMTQ0NzQsImp0aSI6IjA2MTIyMzE5YzZmMTRlODQ4ZGYzZWZiMmFkYzY2ZDM3IiwidXNlcl9pZCI6IjEifQ.e5HH-5e87RVeJwQNtYkiyzf-Wl9YT_XPmYE31f_ow1Q

{
    "name": "Edited Coffee Machine",
    "description": "Fuga in rem, dolores nisi ab, quasi eos dolores quod ex unde cumque repellat rerum. Dicta tempore eligendi error dignissimos atque molestias officia et itaque libero, repellat quod nemo culpa corrupti impedit similique laboriosam esse facilis sapiente, possimus similique animi quasi expedita tenetur iste deleniti nesciunt distinctio quaerat, necessitatibus iusto similique iste ea assumenda nesciunt atque commodi hic ullam, exercitationem inventore aliquam animi.",
    "price": "70.99",
    "stock": 6
}


### 

DELETE  http://localhost:8000/api/products/1/ HTTP/1.1


###
GET http://localhost:8000/api/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgzMDc0NjIyLCJpYXQiOjE3ODMwNzQzMjIsImp0aSI6ImI4YTE1ZTAyZDFmNjRjOGFhYTRhODgzNDFmYTE3MTE3IiwidXNlcl9pZCI6IjIifQ.-blTgVfP0gZZXUBqvAMo-ApdB5ojZZex-UwAcOTnXpE

###
GET http://localhost:8000/api/orders/5ef67642-946e-4338-b93d-9c14e172fe01/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgzMTM2NDI2LCJpYXQiOjE3ODMxMzYxMjYsImp0aSI6Ijc4Y2FmM2I3YWI4MDQ2MjJhODQyN2FkNzJiNWM1NmE5IiwidXNlcl9pZCI6IjEifQ.SlQOTsL1ypBgv38Yd9Z675bxI1mqyG9lyxs8mbP8LHg


###
POST http://localhost:8000/api/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgzMDk4OTY2LCJpYXQiOjE3ODMwOTg2NjYsImp0aSI6ImUyZTIzYTVlZDRlZDRiNmNhOGY1ZGNhYWU1MmZkZTNlIiwidXNlcl9pZCI6IjEifQ.faIeYmMLf3dycvuEw2MkFu2OXH1eXA_TiXRaAaoS70I

{
  "status": "Pending",
  "items": [
    {
      "product": 3,
      "quantity": 5
    },
    {
      "product": 2,
      "quantity": 5
    }
  ]
}


###
PUT http://localhost:8000/api/orders/5ef67642-946e-4338-b93d-9c14e172fe01/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgzMTM4NDQxLCJpYXQiOjE3ODMxMzgxNDEsImp0aSI6IjNmNjc4YTAwYjA2YzQzZDU4NGU2YzE1MWMyM2I4MjU4IiwidXNlcl9pZCI6IjEifQ.74DMPtfveNGcqWmSRIHfnxocR4br11OVAxiED1oXMo8

{
  "status": "Confirmed"
}